### ISSUE TITLE
I have a problem with this program, please help

### ISSUE THREAD

**Issue by mohmmadassaf** [Igor55x/UAAE#55] opened 2022-01-25 18:40 UTC
Can you help me solve this problem..it is very hindering my work

![dd](https://user-images.githubusercontent.com/78138126/151038521-53cdf65c-f1b8-4483-9412-09d165613390.png)

Please explain to me how I can solve this problem

**Comment by Igor55x** [comment] 2022-01-25 21:43
> Can you help me solve this problem..it is very hindering my work

First, are you using the latest release?
If not, than I will release a fix for this bug in a while.
Second, tell me where this problem occurs.
Also attach a stack trace and the problem file.

**Comment by mohmmadassaf** [comment] 2022-01-25 21:47
My friend, I am using the latest version of the program and I always get
this problem and I have updated my Windows, but the problem persists I am
using version 1.2

في الثلاثاء، ٢٥ يناير ٢٠٢٢ ١١:٤٤ م Igor55 ***@***.***> كتب:

**Comment by mohmmadassaf** [comment] 2022-01-25 22:09
My friend, I am using the latest version of the program and I always get this problem and I have updated my Windows, but the problem persists.... I am using version 1.2

**Comment by mohmmadassaf** [comment] 2022-01-27 11:41
My friend, can you help me as soon as possible
I can't do my work because of this problem

![ff](https://user-images.githubusercontent.com/78138126/151352116-66b2aec8-15bc-4b15-89c7-77dc817af9a1.png)


![ww](https://user-images.githubusercontent.com/78138126/151352142-31323701-8beb-4f22-9647-f7eda06e96cd.png)

**Comment by italo13LP** [comment] 2022-01-30 22:40
Maybe I can help u, Im using older version but it works well and its just little custom.
I hope it will help.

[UAAE-Windows-Custom.zip](https://github.com/Igor55x/UAAE/files/7967090/UAAE-Windows-Custom.zip)

**Comment by rowanbean1960** [comment] 2022-02-04 06:08
Problem with ViewData and export.
Doesn't work, still getting that error while trying to export MonoBehaviour.
I guess it's because of the newer unity version.
I think this is it. (From unityplayer.dll-Product version 2021.1.11.4394530) 
The latest version on the list is 2020.3.12 f1.
When are more versions going to be added especially newer versions?
Maybe it will work then.

```
See the end of this message for details on invoking
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
at AssetsAdvancedEditor.Assets.AssetsWorkspace.GetMonoBaseField(AssetItem item, String managedPath) in D:\a\UAAE\UAAE\AssetsAdvancedEditor\Assets\AssetsWorkspace.cs:line 235
at AssetsAdvancedEditor.Assets.AssetsWorkspace.GetBaseField(AssetItem item) in D:\a\UAAE\UAAE\AssetsAdvancedEditor\Assets\AssetsWorkspace.cs:line 213
at AssetsAdvancedEditor.Assets.AssetExporter.ExportDump(String path, AssetItem item, DumpType dumpType) in D:\a\UAAE\UAAE\AssetsAdvancedEditor\Assets\AssetExporter.cs:line 30
at AssetsAdvancedEditor.Winforms.AssetsViewer.SingleExportDump(AssetItem selectedItem) in D:\a\UAAE\UAAE\AssetsAdvancedEditor\Winforms\AssetsViewer.cs:line 536
at AssetsAdvancedEditor.Winforms.AssetsViewer.btnExportDump_Click(Object sender, EventArgs e) in D:\a\UAAE\UAAE\AssetsAdvancedEditor\Winforms\AssetsViewer.cs:line 483
at System.Windows.Forms.Control.OnClick(EventArgs e)
at System.Windows.Forms.Button.OnClick(EventArgs e)
at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
at System.Windows.Forms.Control.WndProc(Message& m)
at System.Windows.Forms.ButtonBase.WndProc(Message& m)
at System.Windows.Forms.Button.WndProc(Message& m)
at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
************** Loaded Assemblies **************
System.Private.CoreLib
Assembly Version: 5.0.0.0
Win32 Version: 5.0.1321.56516
CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.13/System.Private.CoreLib.dll
AssetsAdvancedEditor
Assembly Version: 1.0.0.0
Win32 Version: 1.0.0.0
CodeBase: file:///C:/Users/jason/Desktop/t/1-extract/UAAE-Windows-Custom/AssetsAdvancedEditor.dll
System.Runtime
Assembly Version: 5.0.0.0
Win32 Version: 5.0.1321.56516
CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.13/System.Runtime.dll
System.Windows.Forms
Assembly Version: 5.0.13.0
Win32 Version: 5.0.1321.56701
CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/5.0.13/System.Windows.Forms.dll
System.Windows.Forms.Primitives
Assembly Version: 5.0.13.0
Win32 Version: 5.0.1321.56701
CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/5.0.13/System.Windows.Forms.Primitives.dll
System.ComponentModel.Primitives
Assembly Version: 5.0.0.0
Win32 Version: 5.0.1321.56516
CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.13/System.ComponentModel.Primitives.dll
System.Runtime.InteropServices
Assembly Version: 5.0.0.0
Win32 Version: 5.0.1321.56516
CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.13/System.Runtime.InteropServices.dll
System.Drawing.Primitives
Assembly Version: 5.0.0.0
Win32 Version: 5.0.1321.56516
CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.13/System.Drawing.Primitives.dll
System.Collections.Specialized
Assembly Version: 5.0.0.0
Win32 Version: 5.0.1321.56516
CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.13/System.Collections.Specialized.dll
System.Console
Assembly Version: 5.0.0.0
Win32 Version: 5.0.1321.56516
CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.13/System.Console.dll
System.Drawing.Common
Assembly Version: 5.0.0.2
Win32 Version: 5.0.1221.52207
CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/5.0.13/System.Drawing.Common.dll
System.Threading
Assembly Version: 5.0.0.0
Win32 Version: 5.0.1321.56516
CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.13/System.Threading.dll
System.Diagnostics.TraceSource
Assembly Version: 5.0.0.0
Win32 Version: 5.0.1321.56516
CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.13/System.Diagnostics.TraceSource.dll
System.Collections
Assembly Version: 5.0.0.0
Win32 Version: 5.0.1321.56516
CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.13/System.Collections.dll
UnityTools
Assembly Version: 2.0.0.0
Win32 Version: 2.0.0.0
CodeBase: file:///C:/Users/jason/Desktop/t/1-extract/UAAE-Windows-Custom/UnityTools.dll
netstandard
Assembly Version: 2.1.0.0
Win32 Version: 5.0.1321.56516
CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.13/netstandard.dll
Microsoft.Win32.Primitives
Assembly Version: 5.0.0.0
Win32 Version: 5.0.1321.56516
CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.13/Microsoft.Win32.Primitives.dll
System.ComponentModel.EventBasedAsync
Assembly Version: 5.0.0.0
Win32 Version: 5.0.1321.56516
CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.13/System.ComponentModel.EventBasedAsync.dll
System.Threading.Thread
Assembly Version: 5.0.0.0
Win32 Version: 5.0.1321.56516
CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.13/System.Threading.Thread.dll
Accessibility
Assembly Version: 4.0.0.0
Win32 Version: 5.0.1321.56701
CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/5.0.13/Accessibility.dll
System.ComponentModel.TypeConverter
Assembly Version: 5.0.0.0
Win32 Version: 5.0.1321.56516
CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.13/System.ComponentModel.TypeConverter.dll
Microsoft.Win32.SystemEvents
Assembly Version: 5.0.0.0
Win32 Version: 5.0.20.51904
CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/5.0.13/Microsoft.Win32.SystemEvents.dll
System.Collections.Concurrent
Assembly Version: 5.0.0.0
Win32 Version: 5.0.1321.56516
CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.13/System.Collections.Concurrent.dll
System.Runtime.Extensions
Assembly Version: 5.0.0.0
Win32 Version: 5.0.1321.56516
CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.13/System.Runtime.Extensions.dll
System.ComponentModel
Assembly Version: 5.0.0.0
Win32 Version: 5.0.1321.56516
CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.13/System.ComponentModel.dll
System.Memory
Assembly Version: 5.0.0.0
Win32 Version: 5.0.1321.56516
CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.13/System.Memory.dll
System.Buffers
Assembly Version: 5.0.0.0
Win32 Version: 5.0.1321.56516
CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.13/System.Buffers.dll
System.Resources.Extensions
Assembly Version: 5.0.0.0
Win32 Version: 5.0.20.51904
CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/5.0.13/System.Resources.Extensions.dll
System.ObjectModel
Assembly Version: 5.0.0.0
Win32 Version: 5.0.1321.56516
CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.13/System.ObjectModel.dll
System.Linq
Assembly Version: 5.0.0.0
Win32 Version: 5.0.1321.56516
CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.13/System.Linq.dll
System.Collections.NonGeneric
Assembly Version: 5.0.0.0
Win32 Version: 5.0.1321.56516
CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.13/System.Collections.NonGeneric.dll
System.IO.FileSystem
Assembly Version: 5.0.0.0
Win32 Version: 5.0.1321.56516
CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.13/System.IO.FileSystem.dll
System.Runtime.CompilerServices.Unsafe
Assembly Version: 5.0.0.0
Win32 Version: 5.0.1321.56516
CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.13/System.Runtime.CompilerServices.Unsafe.dll
System.Drawing
Assembly Version: 5.0.13.0
Win32 Version: 5.0.1321.56701
CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/5.0.13/System.Drawing.dll
Microsoft.Win32.Registry
Assembly Version: 5.0.0.0
Win32 Version: 5.0.1321.56516
CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.13/Microsoft.Win32.Registry.dll
System.Text.RegularExpressions
Assembly Version: 5.0.0.0
Win32 Version: 5.0.1321.56516
CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.13/System.Text.RegularExpressions.dll
Mono.Cecil
Assembly Version: 0.11.3.0
Win32 Version: 0.11.3.0
CodeBase: file:///C:/Users/jason/Desktop/t/1-extract/UAAE-Windows-Custom/Mono.Cecil.dll
Plugins
Assembly Version: 1.0.0.0
Win32 Version: 1.0.0.0
CodeBase: file:///C:/Users/jason/Desktop/t/1-extract/UAAE-Windows-Custom/Plugins.dll
System.Threading.ThreadPool
Assembly Version: 5.0.0.0
Win32 Version: 5.0.1321.56516
CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.13/System.Threading.ThreadPool.dll
System.Private.Uri
Assembly Version: 5.0.0.0
Win32 Version: 5.0.1321.56516
CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.13/System.Private.Uri.dll
System.Diagnostics.StackTrace
Assembly Version: 5.0.0.0
Win32 Version: 5.0.1321.56516
CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.13/System.Diagnostics.StackTrace.dll
System.Reflection.Metadata
Assembly Version: 5.0.0.0
Win32 Version: 5.0.1321.56516
CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.13/System.Reflection.Metadata.dll
System.Collections.Immutable
Assembly Version: 5.0.0.0
Win32 Version: 5.0.1321.56516
CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.13/System.Collections.Immutable.dll

************** JIT Debugging **************
```
Please help.

**Comment by raDiesle** [comment] 2022-02-05 17:48
same here

**Comment by rowanbean1960** [comment] 2022-02-06 20:01
I am also using version 1.2 by the way.
Igor55x Should update classdata with all unity versions 2020-lasest 2021.
This should be a priority before anything else to at least get importing and exporting
to work right. Also make sure all information in the files are shown in extracted assets like MonoBehaviour and Monoscript.

**Comment by rowanbean1960** [comment] 2022-02-14 21:25
OK this is weird. When I load the whole game folder Happy Quest with Asset Studio .net6. v0.16.21, I get cab as assets that show up as assets. The versions of 
unity Assets Advanced Editor will not pick up these (hidden I guess) assets
because the whole game folder cannot be loaded and no other asset tool 
can import the files back. Does any else know about these cab assets?
![hidden assets](https://user-images.githubusercontent.com/99003841/153948868-d806fb1e-afae-4774-89d8-e233125ded75.png)

**Comment by Igor55x** [comment] 2022-02-26 12:10
I hope the problem is fixed in 888c5e0.
**Let me know if anything is still not working correctly.**

**Closed by Igor55x** 2022-02-26 12:10 UTC
Labels: bug

**Comment by rowanbean1960** [comment] 2022-03-03 21:21
> I hope the problem is fixed in [888c5e0](https://github.com/Igor55x/UAAE/commit/888c5e0e26c0bf912e03b70917b85d9b1e5d116a). **Let me know if anything is still not working correctly.**

Well hi Igor55x, nice to see a post from you. I need to ask, have you already released the fix or are you working on it?

**Comment by Igor55x** [comment] 2022-03-07 10:40
> I need to ask, have you already released the fix or are you working on it?

Yes, I've already released a fix.
> Do I need to download download the latest build or latest release

You need to download the latest build, because this problem still exists in the latest release.
> I am also not sure how to replace audio as there is no plugin to
extract files as what they are (mp3, wav, ogg etc) ...

This isn't possible atm, because I haven't implemented this plugin yet.
All you can do now is take a program (like `AssetStudio`) and export the audio files, but you can't import them back.
> ... and the import raw
should be able to import back the mp3, wav, ogg etc.

Indeed, any asset(s) can be imported/exported in raw format, but editing an asset(s) in this way is quite difficult.

**Comment by rowanbean1960** [comment] 2022-03-08 02:02
Thanks Igor55, I guess it will just take time to get everything worked out.
I am 47 and still love to mod assets for game cheats and I also use dnspy.
I hope I'M not 60 when you get it completely finished, lol.
I wish you had help. Anyway keep up the good work.
It's great people like you that make it possible for little people like me to enjoy things
like this. (GAME MODDING CHEATS)
Thanks again. 👍

**Comment by rowanbean1960** [comment] 2022-03-14 15:27
Hay Igor55, is there any way for you to add a quick update that allows you to select more then one asset
instead of having to select one at a time?
I want to select all shared assets and extract them.

**Comment by rowanbean1960** [comment] 2022-04-15 18:07
@Igor55x  I found something weird.
On all UAAE version (yes all 1, 1.2 1.3) when I open assets the unity version is 2021.1.22f1 so I used the closest version and tried others and when I select all the MonoBehaviour, export them, it is asking me to select a folder for every single one of them instead of just exporting them all to the folder I selected and this is happening for all dump export types.  version 1.3 is also not giving the names of MonoBehaviour assets and listing them all as unnamed, but I used UABE Avalonia 3 and it exported them all fine and it even give the names of all the MonoBehaviour assets that has names. I still doesn't look ether is giving all the information in the assets though just a little of it compared to all the information you see when select view date. Just found out if you select view date  and select the games Managed folder, it gives you all the information about the asset but you can't do that before exporting them.
I'm confused, what is going on? I do thank you for all your hard work on this.
